name: Deploy to Hosting

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create deployment archive
        run: |
          # Исключаем ненужные файлы
          tar -czf deploy.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='deploy.tar.gz' \
            .
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script_timeout: 10m
          script: |
            echo "=== Starting deployment ==="
            cd /home/c/${{ secrets.SERVER_USER }}
            
            rm -f deploy.tar.gz
            
            start_time=$(date +%s)
            
            mkdir -p temp_deploy
            echo "Directory created"
            
            echo "Copying archive..."
            scp -o StrictHostKeyChecking=no ${{ github.workspace }}/deploy.tar.gz .
            
            echo "Extracting files..."
            tar -xzf deploy.tar.gz -C temp_deploy
            
            echo "Moving public files..."
            mkdir -p public_html
            rsync -a --delete temp_deploy/public/ public_html/
            
            echo "Copying other files..."
            find temp_deploy -mindepth 1 -maxdepth 1 -not -name public -exec cp -r {} . \;
            
            echo "Cleaning up..."
            rm -rf temp_deploy deploy.tar.gz
            
            echo "Setting permissions..."
            find . -type d -exec chmod 755 {} \;
            find . -type f -exec chmod 644 {} \;
            chmod -R 755 public_html
            
            echo "Deployment complete!"
            
            end_time=$(date +%s)
            echo "Deployment took $((end_time - start_time)) seconds"
            

      - name: Create .env
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat > /home/c/${{ secrets.SERVER_USER }}/.env <<EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}
            GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}
            JWT_ACCESS_SECRET=${{secrets.JWT_ACCESS_SECRET}}
            JWT_REFRESH_SECRET=${{secrets.JWT_REFRESH_SECRET}}
            EOF
            chmod 600 /home/c/${{ secrets.SERVER_USER }}/.env